apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: host-operator-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: host-operator-secret
  type: Opaque
  stringData:
    mailgun.api.key: ${MAILGUN_API_KEY}
    mailgun.domain: ${MAILGUN_DOMAIN}
    mailgun.sender.email: ${MAILGUN_SENDER_EMAIL}
    mailgun.replyto.email: ${MAILGUN_REPLYTO_EMAIL}
    twilio.account.sid: ${TWILIO_ACCOUNT_SID}
    twilio.auth.token: ${TWILIO_AUTH_TOKEN}
    twilio.from_number: ${TWILIO_FROM_NUMBER}
parameters:
- name: MAILGUN_API_KEY
- name: MAILGUN_DOMAIN
- name: MAILGUN_SENDER_EMAIL
- name: MAILGUN_REPLYTO_EMAIL
- name: TWILIO_ACCOUNT_SID
- name: TWILIO_AUTH_TOKEN
- name: TWILIO_FROM_NUMBER
